version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${TECH_CHALLENGE_USER}
      POSTGRES_PASSWORD: ${TECH_CHALLENGE_PASSWORD}
      POSTGRES_DB: ${TECH_CHALLENGE_DB_NAME}
    volumes:
      - volume-postgres:/var/lib/postgresql/data

  app:
    build:
      context: .         # Pasta onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: ${TECH_CHALLENGE_USER}
      SPRING_DATASOURCE_PASSWORD: ${TECH_CHALLENGE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${TECH_CHALLENGE_DB_NAME}

volumes:
  volume-postgres: