version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${TECH_CHALLENGE_USER}
      POSTGRES_PASSWORD: ${TECH_CHALLENGE_PASSWORD}
      POSTGRES_DB: ${TECH_CHALLENGE_DB_NAME}
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TECH_CHALLENGE_USER} -d ${TECH_CHALLENGE_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .         # Pasta onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: ${TECH_CHALLENGE_USER}
      SPRING_DATASOURCE_PASSWORD: ${TECH_CHALLENGE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${TECH_CHALLENGE_DB_NAME}

volumes:
  volume-postgres: